# Simply execute 'make' to verify things still build

name: Build All

on:
  push:
    branches:
      - master
      - 'tr_*'

  # Allows running manually
  workflow_dispatch:
    inputs:
      use-latest-translations:
        required: false
        default: false
        description: 'Use latest translations from shared Google Docs sheet'

jobs:
  build:
    runs-on: ubuntu-18.04
    container: docker://variantxyz/rgbds-20200806:cb4fbdfcd534e43a5f8504b405acd7b8b29f5001

    steps:
      - name: List versions
        run: |
          git --version
          python --version
          rgbasm --version
          rgblink --version
          rgbgfx --version

      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          path: 'medarot3'

      - name: Checkout baserom repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.BASEROM3_REPOSITORY }}
          ssh-key: ${{ secrets.BASEROM3_KEY }}
          path: 'baserom'

      - name: Copy baserom into main repository
        run: |
          cp $GITHUB_WORKSPACE/baserom/*.gbc $GITHUB_WORKSPACE/medarot3

      - name: Get latest text from source
        if: github.event.inputs.use-latest-translations
        working-directory: 'medarot3'
        env:
          TRANSLATION_SHEET: sheet.xlsx
        run: |
          wget -q --no-check-certificate "${{ secrets.TRANSLATION_SHEET_URL_SOURCE }}" -O $TRANSLATION_SHEET
          make csv_from_xlsx

      - name: Make all
        working-directory: 'medarot3'
        run: |
          make -j all

      - name: Generate IPS files
        working-directory: 'medarot3'
        run: |
          ips_util create baserom_kabuto.gbc medarot3_kabuto.gbc -o m3kabuto-$GITHUB_RUN_NUMBER-$GITHUB_SHA.ips
          ips_util create baserom_kuwagata.gbc medarot3_kuwagata.gbc -o m3kuwagata-$GITHUB_RUN_NUMBER-$GITHUB_SHA.ips

      - name: 'Archive IPS files'
        uses: actions/upload-artifact@v2
        with:
          name: ips_files
          path: medarot3/*.ips
          retention-days: 1

      - name: Verify no new untracked files were added
        working-directory: 'medarot3'
        if: github.event.inputs.use-latest-translations != true
        run: |
          git diff --quiet --exit-code && exit 0 || exit 1

