# Simply execute 'make' to verify things still build

name: Build All

on:
  push:
    branches:
      - master
      - 'tr_*'
  pull_request_target:
    branches:
      - master
      - 'tr_*'

  # Allows running manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    container: docker://variantxyz/rgbds-20200806:cb4fbdfcd534e43a5f8504b405acd7b8b29f5001

    steps:
      - uses: actions/checkout@v2

      - name: Print tool versions
        run: |
          python --version
          rgbasm --version
          rgblink --version
          rgbgfx --version